apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-test
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-test
    spec:
      containers:
      - name: server
        image: "index.docker.io/netchris/hellotest:dev"
        resources:
          requests: {cpu: 50m}
          limits: {memory: 64Mi}
