apiVersion: v1
kind: ConfigMap
metadata:
  name: templatetest-defaults
data:
  SPARK_DRIVER_MEMORY: 1g
  SPARK_EXECUTOR_INSTANCES: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: templatetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templatetest
      spark-role: driver
  template:
    metadata:
      labels:
        app: templatetest
        spark-role: driver
    spec:
      containers:
      - name: spark-kubernetes-driver
        image: index.docker.io/netchris/templatetest:dev
        imagePullPolicy: Always
        terminationMessagePolicy: FallbackToLogsOnError
        args:
        - 10.150.144.151
        envFrom:
        - configMapRef: {optional: false, name: templatetest-defaults}
        - configMapRef: {optional: true,  name: templatetest-overrides}
        env:
        - name: POD_NAME
          valueFrom: {fieldRef: {fieldPath: metadata.name}}
        - name: POD_NAMESPACE
          valueFrom: {fieldRef: {fieldPath: metadata.namespace}}
        - name: POD_IP
          valueFrom: {fieldRef: {fieldPath: status.podIP}}
        - name: POD_SERVICE_ACCOUNT_NAME
          valueFrom: {fieldRef: {fieldPath: spec.serviceAccountName}}
        resources:
          limits:
            memory: 1408Mi
          requests:
            cpu: "1"
            memory: 1Gi